create table permission_table
(
    id         bigint generated by default as identity   not null,
    code       varchar(64)                               not null,
    name       varchar(32)                               not null,
    description text,
    created_at timestamp(6) with time zone default now() not null,
    updated_at  timestamp(6) with time zone,

    primary key (id),

    constraint uk_permission_code unique (code)
);

create table role_table
(
    id         bigint generated by default as identity   not null,
    code       varchar(64)                               not null,
    name       varchar(32)                               not null,
    description text,
    created_at timestamp(6) with time zone default now() not null,
    updated_at  timestamp(6) with time zone,

    primary key (id),

    constraint uk_role_code unique (code)
);

create table role_permission_table
(
    role_id       bigint                                    not null,
    permission_id bigint                                    not null,
    created_at    timestamp(6) with time zone default now() not null,
    updated_at    timestamp(6) with time zone,

    primary key (role_id, permission_id),
    foreign key (role_id) references role_table (id),
    foreign key (permission_id) references permission_table (id)
);

create table user_table
(
    id         bigint generated by default as identity   not null,
    nickname   varchar(20)                               not null,
    avatar     text,
    username   varchar(20)                               not null,
    email      varchar(254),
    password   varchar(60)                               not null,
    status     boolean                                   not null,
    created_at timestamp(6) with time zone default now() not null,
    updated_at timestamp(6) with time zone,

    primary key (id),

    constraint uk_user_username unique (username),
    constraint uk_user_email unique (email)
);

create table user_role_table
(
    user_id    bigint                                    not null,
    role_id    bigint                                    not null,
    created_at timestamp(6) with time zone default now() not null,
    updated_at timestamp(6) with time zone,

    primary key (user_id, role_id),

    foreign key (user_id) references user_table (id),
    foreign key (role_id) references role_table (id)
);

create table refresh_token_table
(
    id         bigint generated by default as identity   not null,
    user_id    bigint                                    not null,
    token_hash varchar(64)                               not null,
    expires_at timestamp(6) with time zone               not null,
    created_at timestamp(6) with time zone default now() not null,
    updated_at     timestamp(6) with time zone,
    last_used_at   timestamp(6) with time zone,
    revoked_at     timestamp(6) with time zone,
    user_agent text,
    ip_address     varchar(45),
    replaced_by_id bigint,

    primary key (id),

    constraint uk_refresh_token_token_hash unique (token_hash),
    unique (replaced_by_id),

    foreign key (replaced_by_id) references refresh_token_table (id),
    foreign key (user_id) references user_table (id)
);


-- ### ---

create table tag_table
(
    id   bigint generated by default as identity not null,
    name varchar(24)                             not null,
    slug text not null,

    primary key (id),

    constraint uk_tag_name unique (name),
    constraint uk_tag_slug unique (slug)
);

create table categories_table
(
    id   bigint generated by default as identity not null,
    name varchar(24)                             not null,
    slug text not null,

    primary key (id),

    constraint uk_categories_name unique (name),
    constraint uk_categories_slug unique (slug)
);

create table article_table
(
    id             bigint generated by default as identity   not null,
    title          text                                      not null,
    slug           text                                      not null,
    featured_image text,
    content        text                                      not null,
    author_id      bigint                                    not null,
    category_id    bigint                                    not null,

    article_status text                                      not null,
    created_at     timestamp(6) with time zone default now() not null,
    updated_at     timestamp(6) with time zone,

    primary key (id),

    constraint uk_article_slug unique (slug),

    foreign key (author_id) references user_table (id),
    foreign key (category_id) references categories_table (id)
);

create table article_tag_table
(
    article_id bigint not null,
    tag_id     bigint not null,

    primary key (article_id, tag_id),

    foreign key (article_id) references article_table (id),
    foreign key (tag_id) references tag_table (id)
);

create table comment_table
(
    id         bigint generated by default as identity   not null,
    content    text                                      not null,
    status     text                                      not null,
    like_count bigint                                    not null,
    article_id bigint                                    not null,
    user_id    bigint                                    not null,
    parent_comment_id bigint,
    created_at timestamp(6) with time zone default now() not null,
    updated_at        timestamp(6) with time zone,
    deleted_at        timestamp(6) with time zone,

    primary key (id),
    foreign key (article_id) references article_table (id),
    foreign key (user_id) references user_table (id),
    foreign key (parent_comment_id) references comment_table (id)
);

create table comment_like_table
(
    id         bigint generated by default as identity   not null,
    comment_id bigint                                    not null,
    user_id    bigint                                    not null,
    created_at timestamp(6) with time zone default now() not null,

    primary key (id),

    constraint uk_comment_like_user_comment unique (comment_id, user_id),

    foreign key (comment_id) references comment_table (id),
    foreign key (user_id) references user_table (id)
);

create type object_storage_purpose as enum (
    'AVATAR', -- 用户头像
    'ARTICLE_IMAGE', -- 文章正文图片
    'ARTICLE_FEATURED_IMAGE', -- 文章封面图
    'ARTICLE_VIDEO', -- 文章视频
    'ARTICLE_ATTACHMENT' -- 文章附件
    );

create type object_storage_status as enum (
    'PREPARED',
    'UPLOADING',
    'UPLOADED',
    'FAILED',
    'DELETED'
    );

create type object_storage_visibility as enum (
    'PUBLIC',
    'PRIVATE'
    );

create table object_storage_table
(
    id                bigint generated by default as identity   not null,
    owner_user_id     bigint                                    not null,
    purpose    object_storage_purpose    not null,
    original_filename text                                      not null,
    content_type      text                                      not null,
    file_size  bigint                    not null,
    file_hash  varchar(64),
    bucket            text                                      not null,
    object_key        text                                      not null,
    status     object_storage_status     not null,
    visibility object_storage_visibility not null,
    created_at        timestamp(6) with time zone default now() not null,
    updated_at        timestamp(6) with time zone,

    primary key (id),
    constraint uk_object_storage_object_key unique (bucket, object_key),
    foreign key (owner_user_id) references user_table (id)
);

create table article_object_storage_table
(
    id                bigint generated by default as identity not null,
    article_id        bigint                                  not null,
    object_storage_id bigint                                  not null,

    primary key (id),
    foreign key (article_id) references article_table (id),
    foreign key (object_storage_id) references object_storage_table (id),
    constraint uk_article_object_storage_article_object_storage unique (article_id, object_storage_id)
)