alter table article_table
    add column like_count bigint not null default 0;

create table article_likes_table
(
    id         bigint generated by default as identity   not null,
    article_id bigint                                    not null,
    user_id    bigint                                    not null,
    created_at timestamp(6) with time zone default now() not null,

    primary key (id),
    constraint uk_article_likes_article_user unique (article_id, user_id),
    foreign key (article_id) references article_table (id) on delete cascade,
    foreign key (user_id) references user_table (id) on delete cascade
);

insert into permission_table(code, name)
values ('article:like', '文章点赞');

insert into role_permission_table(role_id, permission_id)
select r.id, p.id
from permission_table p
         join role_table r on r.code in ('admin', 'user')
where p.code = 'article:like';