alter table article_table
    add column like_count bigint not null default 0;

create table article_likes
(
    id         bigint generated by default as identity   not null,
    article_id bigint                                    not null,
    user_id    bigint                                    not null,
    created_at timestamp(6) with time zone default now() not null,

    primary key (id),
    constraint uk_article_likes_article_user unique (article_id, user_id),
    foreign key (article_id) references article_table (id) on delete cascade,
    foreign key (user_id) references user_table (id) on delete cascade
);


